version: "3.7"
services:
  flask:
    build: ./flask
    container_name: flaskplt
    restart: always
    environment:
      - REDIS_HOST=redis6
      - REDIS_PORT=6379
    ports:
      - "9999:9999"

  redis:
    image: redis:6
    restart: always
    container_name: redis6
    ports:
      - "6379:6379"